networks:
  app-network:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  product-review-processor:
    build:
      context: .
      dockerfile: apps/product-review-processor/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
